run:
  timeout: 3m
  issues-exit-code: 1
  tests: false

output:
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true

  enable:
    #     required
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - gosec
    - durationcheck
    - contextcheck

    #     optional
    - unused
    - bodyclose
    - misspell
    - musttag
    - nilerr
    - prealloc
    - whitespace
