{
 "title": "Go Processes",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": "label_values(go_memstats_alloc_bytes{account=\"kufar-pro\"}, app)"
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{app=\"$app\"}) by (app)",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "sum(rate(go_memstats_alloc_bytes_total{app=\"$app\"}[$__interval])) by (app)",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "sum(go_memstats_stack_inuse_bytes{app=\"$app\"}) by (app)",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{app=\"$app\"}) by (app)",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(deriv(go_memstats_alloc_bytes{app=\"$app\"}[$interval])) by (app)",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "sum(rate(go_memstats_alloc_bytes_total{app=\"$app\"}[$interval])) by (app)",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "avg(deriv(go_memstats_stack_inuse_bytes{ app=\"$app\"}[$interval])) by (app)",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "avg(deriv(go_memstats_heap_inuse_bytes{app=\"$app\"}[$interval])) by (app)",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_open_fds{ app=\"$app\"}) by (app)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{app=\"$app\"}[$interval])"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{app=\"$app\"}) by (app)",
     "legendFormat": "{{goroutines}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(go_gc_duration_seconds{app=\"$app\"}) by (app, quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}