{
 "title": "son",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "apihandler",
    "label": "search-api transport handler",
    "query": {
     "query": "label_values(requests_total{appName=\"son\"},handler)"
    }
   },
   {
    "name": "statustinterval",
    "label": "status table interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "DS_PROMETHEUS_PRO", "query": "prometheus" },
   {
    "name": "storieshandlers",
    "query": {
     "query": "label_values(requests_total{appName=\"son\"},handler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "son throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(response_size_bytes_sum{appName=\"son\"}[$__interval])) by (handler) \n",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "son RPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requests_total{appName=\"son\"}[$__interval])) by (handler) \n",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "$apihandler latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "repeat": "apihandler",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{appName=\"son\", handler=~\"$apihandler\"}[$__interval])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket{appName=\"son\", handler=~\"$apihandler\"}[$__interval])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(request_duration_seconds_bucket{appName=\"son\", handler=~\"$apihandler\"}[$__interval])) by (le))",
     "legendFormat": "0.90"
    }
   ]
  },
  {
   "title": "Endpoints over last $statustinterval",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum by (code, handler, app) (increase(requests_total{appName=\"son\"}[$statustinterval]))"
    }
   ]
  },
  {
   "title": "QoS (son/2m)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (sum(increase(requests_total{appName=\"son\",code=~\"5..\"}[2m])) / \nsum(increase(requests_total{appName=\"son\"}[2m])) * 100)",
     "legendFormat": "QoS"
    },
    {
     "expr": "sum(increase(requests_total{account=\"kufar-pro\",appName=\"searchapi\"}[2m]))",
     "legendFormat": "reqs"
    },
    {
     "expr": "sum(increase(requests_total{account=\"kufar-pro\",appName=\"searchapi\",code=~\"4..\"}[2m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(requests_total{account=\"kufar-pro\",appName=\"searchapi\",code=~\"5..\"}[2m]))",
     "legendFormat": "5xx"
    }
   ]
  }
 ]
}